Controllers/ConsumptionsController.cs
using AspnetCoreMvcFull.Core.Context;
using AspnetCoreMvcFull.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AspnetCoreMvcFull.Controllers
{
  public class ConsumptionsController : Controller
  {
    private readonly ApplicationDbContext _context;

    public ConsumptionsController(ApplicationDbContext context)
    {
      _context = context;
    }

    public IActionResult Index(string userId, int? groupId, int? productId, DateTime? startDate, DateTime? endDate)
    {
      var consumptions = _context.Consumptions.Include(c => c.User).Include(c => c.Product).AsQueryable();

      // اعمال فیلترها
      if (!string.IsNullOrEmpty(userId))
      {
        consumptions = consumptions.Where(c => c.UserId == userId);
        ViewBag.FilterUserId = userId;
      }
      if (groupId.HasValue)
      {
        consumptions = consumptions.Where(c => c.User.GroupId == groupId);
        ViewBag.FilterGroupId = groupId;
      }
      if (productId.HasValue)
      {
        consumptions = consumptions.Where(c => c.ProductId == productId);
        ViewBag.FilterProductId = productId;
      }
      if (startDate.HasValue)
      {
        consumptions = consumptions.Where(c => c.ConsumptionTime >= startDate.Value);
        ViewBag.FilterStartDate = startDate.Value.ToString("yyyy-MM-dd");
      }
      if (endDate.HasValue)
      {
        consumptions = consumptions.Where(c => c.ConsumptionTime <= endDate.Value);
        ViewBag.FilterEndDate = endDate.Value.ToString("yyyy-MM-dd");
      }

      // ارسال تعداد نتایج
      ViewBag.RowCount = consumptions.Count();

      // ارسال داده‌ها
      ViewBag.Users = _context.Users.ToList();
      ViewBag.Groups = _context.Groups.ToList();
      ViewBag.Products = _context.Products.ToList();

      return View(consumptions.ToList());
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
      var consumption = _context.Consumptions
          .Include(c => c.User)
          .Include(c => c.Product)
          .FirstOrDefault(c => c.Id == id);

      if (consumption == null)
      {
        return NotFound();
      }

      ViewBag.Products = _context.Products.ToList();
      ViewBag.Users = _context.Users.ToList();
      ViewBag.Groups = _context.Groups.ToList();

      return View(consumption);
    }

    [HttpPost]
    public IActionResult EditConsumption(Consumption updatedConsumption)
    {
      if (!ModelState.IsValid)
      {
        ViewBag.Products = _context.Products.ToList();
        ViewBag.Users = _context.Users.ToList();
        ViewBag.Groups = _context.Groups.ToList();
        return View(updatedConsumption);
      }

      var existingConsumption = _context.Consumptions.FirstOrDefault(c => c.Id == updatedConsumption.Id);

      if (existingConsumption == null)
      {
        return NotFound();
      }

      existingConsumption.ProductId = updatedConsumption.ProductId;
      existingConsumption.Quantity = updatedConsumption.Quantity;
      existingConsumption.ConsumptionTime = updatedConsumption.ConsumptionTime;

      _context.SaveChanges();

      return RedirectToAction("Index");
    }


  }

}

Controllers/DashboardsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace AspnetCoreMvcFull.Controllers;

[Authorize]
public class DashboardsController : Controller
{
  public IActionResult Index()
  {
    return View();
  }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Core.Context;
using AspnetCoreMvcFull.Models.User;
using Microsoft.EntityFrameworkCore;
using AspnetCoreMvcFull.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using AspnetCoreMvcFull.Models.ViewModels;

namespace AspnetCoreMvcFull.Controllers
{
  public class ProductsController : Controller
  {
    private readonly ApplicationDbContext _context;

    public ProductsController(ApplicationDbContext context)
    {
      _context = context;
    }

    // GET: Products
    public async Task<IActionResult> Index()
    {
      var products = await _context.Products
          .Include(p => p.Group)
          .ToListAsync();
      return View(products);
    }

    // GET: Products/Create
    public async Task<IActionResult> Create()
    {
      ViewData["GroupId"] = new SelectList(await _context.Groups.ToListAsync(), "Id", "Name");
      return View();
    }

    // POST: Products/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,GroupId")] ProductRequest productRequest)
    {
      Product product = new Product
      {
        Id = productRequest.Id,
        GroupId = productRequest.GroupId,
        Name = productRequest.Name
      };

      if (ModelState.IsValid)
      {
        _context.Add(product);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      ViewData["GroupId"] = new SelectList(await _context.Groups.ToListAsync(), "Id", "Name", product.GroupId);
      return View(product);
    }

    // GET: Products/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
        return NotFound();

      var product = await _context.Products.FindAsync(id);
      if (product == null)
        return NotFound();

      ViewData["GroupId"] = new SelectList(await _context.Groups.ToListAsync(), "Id", "Name", product.GroupId);
      return View(product);
    }

    // POST: Products/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,GroupId")] ProductRequest productRequest)
    {
      if (id != productRequest.Id)
        return NotFound();

      Product product = new Product
      {
        Id = productRequest.Id,
        GroupId = productRequest.GroupId,
        Name = productRequest.Name
      };

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(product);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!ProductExists(product.Id))
            return NotFound();
          else
            throw;
        }
        return RedirectToAction(nameof(Index));
      }
      ViewData["GroupId"] = new SelectList(await _context.Groups.ToListAsync(), "Id", "Name", product.GroupId);
      return View(product);
    }

    // GET: Products/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
        return NotFound();

      var product = await _context.Products
          .Include(p => p.Group)
          .FirstOrDefaultAsync(m => m.Id == id);
      if (product == null)
        return NotFound();

      return View(product);
    }

    // POST: Products/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var product = await _context.Products.FindAsync(id);
      _context.Products.Remove(product);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool ProductExists(int id)
    {
      return _context.Products.Any(e => e.Id == id);
    }
  }
}

Controllers/UserGroupsController.cs
using Microsoft.AspNetCore.Mvc;
using AspnetCoreMvcFull.Core.Context;
using AspnetCoreMvcFull.Models.User;
using Microsoft.EntityFrameworkCore;

namespace AspnetCoreMvcFull.Controllers
{
  public class UserGroupsController : Controller
  {
    private readonly ApplicationDbContext _context;

    public UserGroupsController(ApplicationDbContext context)
    {
      _context = context;
    }

    // GET: UserGroups
    public async Task<IActionResult> Index()
    {
      var userGroups = await _context.Groups.ToListAsync();
      return View(userGroups);
    }

    // GET: UserGroups/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null)
        return NotFound();

      var userGroup = await _context.Groups
          .Include(g => g.Users)
          .Include(g => g.Products)
          .FirstOrDefaultAsync(m => m.Id == id);

      if (userGroup == null)
        return NotFound();

      return View(userGroup);
    }

    // GET: UserGroups/Create
    public IActionResult Create()
    {
      return View();
    }

    // POST: UserGroups/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name")] UserGroup userGroup)
    {
      if (ModelState.IsValid)
      {
        _context.Add(userGroup);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      return View(userGroup);
    }

    // GET: UserGroups/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
        return NotFound();

      var userGroup = await _context.Groups.FindAsync(id);
      if (userGroup == null)
        return NotFound();

      return View(userGroup);
    }

    // POST: UserGroups/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] UserGroup userGroup)
    {
      if (id != userGroup.Id)
        return NotFound();

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(userGroup);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!UserGroupExists(userGroup.Id))
            return NotFound();
          else
            throw;
        }
        return RedirectToAction(nameof(Index));
      }
      return View(userGroup);
    }

    // GET: UserGroups/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
        return NotFound();

      var userGroup = await _context.Groups
          .FirstOrDefaultAsync(m => m.Id == id);

      if (userGroup == null)
        return NotFound();

      return View(userGroup);
    }

    // POST: UserGroups/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var userGroup = await _context.Groups.FindAsync(id);
      _context.Groups.Remove(userGroup);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool UserGroupExists(int id)
    {
      return _context.Groups.Any(e => e.Id == id);
    }
  }
}

Views/Shared/Sections/Menu/_VerticalMenu.cshtml
@{
    TempData.Keep();
    string? currentPage = ViewContext.HttpContext.Request.Path;
}

<!-- Menu -->
@* ! Do this simple *@
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">

    @* ! Hide app brand if navbar-full *@
    <div class='app-brand demo @((@ViewData["navbarFull"] != null && Convert.ToBoolean(@ViewData["navbarFull"])) ? "d-xl-none" : "")'>
        <a asp-controller="Dashboards" asp-action="Index" class="app-brand-link">
            <span class="app-brand-logo demo">
                @await Html.PartialAsync("../_Partials/_Macros")
            </span>
            <span class="app-brand-text demo menu-text fw-bold ms-2">@TempData.Peek("appName")</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm d-flex align-items-center justify-content-center"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    @* ! Full version menu-items *@
    <ul class="menu-inner py-1">
        <!-- Dashboards -->
        <li class='menu-item@(currentPage.EndsWith("/") || currentPage.StartsWith("/Dashboards/") ? " active open" : "")'>
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-home-smile"></i>
                <div class="text-truncate" data-i18n="Dashboards">Dashboards</div>
                <span class="badge rounded-pill bg-danger ms-auto">5</span>
            </a>
            <ul class="menu-sub">
                <li class='menu-item@(currentPage == "/" ? " active" : "")'>
                    <a asp-controller="Dashboards" asp-action="Index" class="menu-link">
                        <div>Analytics</div>
                    </a>
                </li>
            </ul>
        </li>


        <!-- participants -->
        <li class="menu-header small text-uppercase">
            <span class="menu-header-text">participants</span>
        </li>

        <!-- Apps -->
        <li class='menu-item@(currentPage == "/Apps/Email" ? " active" : "")'>
            <a href="" target="_blank" class="menu-link">
                <i class="menu-icon tf-icons bx bx-envelope"></i>
                <div>Support</div><div class="badge bg-label-primary fs-tiny rounded-pill ms-auto text-uppercase">Unread</div>
            </a>
        </li>

        <!-- Pages -->
        <li class='menu-item@(currentPage.Contains("Participants") ? " active open" : "")'>
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-user"></i>
                <div>Participants</div>
            </a>
            <ul class="menu-sub">
                <li class='menu-item@(currentPage == "/Participants/Create" ? " active" : "")'>
                    <a asp-controller="Participants" asp-action="Create" class="menu-link">
                        <div>Add New</div>
                    </a>
                </li>
                <li class='menu-item@(currentPage == "/Participants/Index" ? " active" : "")'>
                    <a asp-controller="Participants" asp-action="Index" class="menu-link">
                        <div>Get All</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class='menu-item@((currentPage.StartsWith("/UserGroups") || 
                                  currentPage.StartsWith("/Products")

                                ) ? " active open" : "")'>
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-data"></i>
                <div>Basic Information</div>
            </a>
            <ul class="menu-sub">
                <li class='menu-item@(currentPage == "/UserGroups/Index" ? " active" : "")'>
                    <a asp-controller="UserGroups" asp-action="Index" class="menu-link">
                        <div>User Groups</div>
                    </a>
                </li>
                <li class='menu-item@(currentPage == "/Auth/RegisterBasic" ? " active" : "")'>
                    <a asp-controller="Products" asp-action="Index" class="menu-link">
                        <div>Products</div>
                    </a>
                </li>
                <li class='menu-item@(currentPage == "/Auth/ForgotPasswordBasic" ? " active" : "")'>
                    <a asp-controller="Auth" asp-action="ForgotPasswordBasic" class="menu-link">
                        <div>Forgot Password</div>
                    </a>
                </li>
            </ul>
        </li>

        <!-- Components -->
        <li class="menu-header small text-uppercase"><span class="menu-header-text">Consumptions</span></li>
        <!-- Cards -->
        <li class='menu-item@(currentPage == "Consumptions/index" ? " active" : "")'>
            <a asp-controller="Consumptions" asp-action="index" class="menu-link">
                <i class="menu-icon tf-icons bx bx-collection"></i>
                <div class="text-truncate" data-i18n="Cards">Consumptions</div>
            </a>
        </li>
        <!-- Misc -->
        <li class="menu-header small text-uppercase"><span class="menu-header-text">Misc</span></li>
        <li class="menu-item">
            <a href='@TempData.Peek("support")' target="_blank" class="menu-link">
                <i class="menu-icon tf-icons bx bx-support"></i>
                <div>Support</div>
            </a>
        </li>
        <li class="menu-item">
            <a href='@TempData.Peek("documentation")' target="_blank" class="menu-link">
                <i class="menu-icon tf-icons bx bx-file"></i>
                <div>Documentation</div>
            </a>
        </li>
    </ul>

</aside>
<!-- / Menu -->